In [22]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
df = pd.read_csv("./datas_ml/Data.csv")

In [24]:
# 온라인 소핑목 고객 데이터라고 가정, 이 소핑목에서 물건을 구매했으면, Purchased 가 yes
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [25]:
# 이 데이터를 가지고 인공지능 만들건데, 고객 데이터를 넣으면, 우리 쇼핑몰에서 물건을 구매할것 같은지 할거 같은지
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
df.shape

(10, 4)

In [8]:
df['Purchased'].value_counts()  

Purchased
No     5
Yes    5
Name: count, dtype: int64

In [11]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [5]:
sorted(df['Country'].unique())

['France', 'Germany', 'Spain']

In [10]:
# sorted(df['Purchased'].unique())
sorted(df['Purchased'].unique())

['No', 'Yes']

In [12]:
# 결측치 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [26]:
df.isna()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [13]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [15]:
df.isna().sum().sum()

np.int64(2)

In [27]:
# 결측치 처리 - 삭제
df1 = df.dropna()
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [28]:
# 결측치 처리 - 채우기
df2 = df.fillna(method='ffill')  # 앞의 값으로 채우기
df2

C:\Users\Admin\AppData\Local\Temp\ipykernel_8716\2602757446.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2 = df.fillna(method='ffill')  # 앞의 값으로 채우기


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  35.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [29]:
df3 = df.fillna(method='bfill')  # 뒤의 값으로 채우기
df3

C:\Users\Admin\AppData\Local\Temp\ipykernel_8716\1204766447.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3 = df.fillna(method='bfill')  # 뒤의 값으로 채우기


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  58000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  48.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [30]:
df4 = df.fillna(df.mean(numeric_only=True))  # 평균값으로 채우기
df4

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [32]:
df.mean(numeric_only=True)

Age          38.777778
Salary    63777.777778
dtype: float64

In [33]:
df = df.dropna()
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [34]:
df = df.reset_index(drop=True)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4   France  35.0  58000.0       Yes
5   France  48.0  79000.0       Yes
6  Germany  50.0  83000.0        No
7   France  37.0  67000.0       Yes

In [40]:
# x,y 데이터를 분리
X = df.loc[:, ['Country', 'Age', 'Salary']]  # 독립변수
y = df['Purchased']  # 종속변수


In [36]:
# label encoding - 범주형 데이터를 숫자로 변환
# 레이블 인코딩은 문자열을 숫자로 변환하는 기법
# one-hot encoding - 범주형 데이터를 0과 1로 이루어진 벡터로 변환
# 예를 들어 'Red', 'Green', 'Blue' 라는 세 가지 범주형 데이터가 있을 때,
# 레이블 인코딩은 Red=0, Green=1, Blue=2 로 변환하지만,
# 원-핫 인코딩은 Red=[1,0,0], Green=[0,1,0], Blue=[0,0,1] 로 변환
# 왜 원-핫 인코딩을 쓰냐면, 레이블 인코딩은 숫자 간에 순서나 크기가 있다고 오해할 수 있기 때문
from sklearn.preprocessing import LabelEncoder , OneHotEncoder


In [41]:
encoder = LabelEncoder()


In [42]:
X['Country'] 

0     France
1      Spain
2    Germany
3      Spain
4     France
5     France
6    Germany
7     France
Name: Country, dtype: object

In [44]:
encoder.fit_transform(X['Country'])

array([0, 2, 1, 2, 0, 0, 1, 0])

In [45]:
X['Country'] = encoder.fit_transform(X['Country'])
X['Country']

0    0
1    2
2    1
3    2
4    0
5    0
6    1
7    0
Name: Country, dtype: int64

In [46]:
X

Country   Age   Salary
0        0  44.0  72000.0
1        2  27.0  48000.0
2        1  30.0  54000.0
3        2  38.0  61000.0
4        0  35.0  58000.0
5        0  48.0  79000.0
6        1  50.0  83000.0
7        0  37.0  67000.0

In [51]:
# One-Hot Encoding
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer( [('encoder', OneHotEncoder(), [0])], remainder='passthrough' )
X = ct.fit_transform(X)
X

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [53]:
# y데이터 인코딩
y =y.map( {'No':0, 'Yes':1} )
y


0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
Name: Purchased, dtype: int64

In [55]:
X[:5]

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [57]:
# x,y 인코딩 후  Feature Scaling 진행 
# Feature Scaling
from sklearn.preprocessing import StandardScaler

In [ ]:
# 표준화
# 객체생성
scaler = StandardScaler()
# 학습 및 변환
X = scaler.fit_transform(X)

In [60]:
scaler.fit_transform(X)

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [ ]:
# 데이터 전처리
# 1.결측치 처리
# 2.x,y 데이터 분리: 독립변수, 종속변수
# 3.인코딩(One-Hot Encoding, Label Encoding) : ML은 숫자데이터만 처리 가능
# 4.Feature Scaling: 데이터 수준 맞추기

In [62]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

array([[ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.]])

In [63]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6, 3), (2, 3), (6,), (2,))